name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Host & User
        run: |
          echo "Host: ${{ secrets.EC2_HOST }}"
          echo "User: ${{ secrets.EC2_USER }}"

      - name: Check SSH Key Exists
        run: |
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "❌ SSH Key missing"
          else
            echo "✅ SSH Key exists"
          fi
